server:
  port: 9001
spring:
  application:
    name: service-user #服务名称
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 199509
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    database: 1
    host: 127.0.0.1
  session:
    store-type: redis
mybatis:
  mapper-locations: classpath:mapping/*.xml
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#    sender:
#      type: web #数据传输的方式，以http的形式向server端发送数据
#  sleuth:
#    sampler:
#      probability: 1 #采样比 收集日志信息的比例
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
#logging:
#  level:
#    root: info
#    org.springframework.web.servlet.DispatcherServlet: debug
#    org.springframework.cloud.sleuth: debug

